# 01 Importing Libraries

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

# 02 Import Data

In [4]:
path = r'C:\Users\isava\OneDrive\Documents\CareerFoundry\Data Immersion\PythonFundamentals\Instacart Basket Analysis'
path

'C:\\Users\\isava\\OneDrive\\Documents\\CareerFoundry\\Data Immersion\\PythonFundamentals\\Instacart Basket Analysis'

In [5]:
df = pd.read_pickle(os.path.join(path,'02 Data', 'Prepared Data','ords_prods_grouped_indicators_cleaned.pkl'))

In [6]:
cust = pd.read_csv(os.path.join(path,'02 Data', 'Original Data','customers.csv'))

# 03 Data Wrangling

In [8]:
cust.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [9]:
cust.describe()

             user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In [10]:
cust['STATE'].value_counts(dropna = False)

STATE
Florida                 4044
Colorado                4044
Illinois                4044
Alabama                 4044
District of Columbia    4044
Hawaii                  4044
Arizona                 4044
Connecticut             4044
California              4044
Indiana                 4044
Arkansas                4044
Alaska                  4044
Delaware                4044
Iowa                    4044
Idaho                   4044
Georgia                 4044
Wyoming                 4043
Mississippi             4043
Oklahoma                4043
Utah                    4043
New Hampshire           4043
Kentucky                4043
Maryland                4043
Rhode Island            4043
Massachusetts           4043
Michigan                4043
New Jersey              4043
Kansas                  4043
South Dakota            4043
Minnesota               4043
Tennessee               4043
New York                4043
Washington              4043
Louisiana               4043
Montana                 4043
North Dakota            4043
Wisconsin               4043
Nebraska                4043
Vermont                 4043
Nevada                  4043
Maine                   4043
North Carolina          4043
West Virginia           4043
Virginia                4043
Oregon                  4043
New Mexico              4043
Texas                   4043
Pennsylvania            4043
Ohio                    4043
South Carolina          4043
Missouri                4043
Name: count, dtype: int64

In [11]:
cust['fam_status'].value_counts(dropna = False)

fam_status
married                             144906
single                               33962
divorced/widowed                     17640
living with parents and siblings      9701
Name: count, dtype: int64

In [12]:
cust['Gender'].value_counts(dropna = False)

Gender
Male      104067
Female    102142
Name: count, dtype: int64

Immediately all of the value summaries and counts seem to make sense. I do see that various of the columns need to  renamed  both to correct spelling errors and to keep consistency.

### Rename Columns

In [15]:
cust.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [16]:
cust.rename(columns = {'First Name' : 'first_name'}, inplace = True)
cust.rename(columns = {'Surnam' : 'last_name'}, inplace = True)
cust.rename(columns = {'Gender' : 'gender'}, inplace = True)
cust.rename(columns = {'STATE' : 'state'}, inplace = True)
cust.rename(columns = {'Age' : 'age'}, inplace = True)
cust.rename(columns = {'n_dependants' : 'n_dependents'}, inplace = True)

cust.head()

,user_id,first_name,last_name,gender,state,age,date_joined,n_dependents,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

# 04 Data Consistency Checks

### Mixed Data Types

In [19]:
for col in cust.columns.tolist():
  weird = (cust[[col]].map(type) != cust[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (cust[weird]) > 0:
    print (col)

first_name

The column first_name appears to have a mixed data type. This column is consist of names onl which are strings so I will make this column string type only.

In [21]:
cust['first_name'] = cust['first_name'].astype('str')
cust['first_name'].dtype

dtype('O')

### Missing Values

In [23]:
cust.isnull().sum()

user_id         0
first_name      0
last_name       0
gender          0
state           0
age             0
date_joined     0
n_dependents    0
fam_status      0
income          0
dtype: int64

No missing values.

### Duplicate Values

In [26]:
cust[cust.duplicated()]

Empty DataFrame
Columns: [user_id, first_name, last_name, gender, state, age, date_joined, n_dependents, fam_status, income]
Index: []

No duplicate values found.

# 05 Merge Data

In [29]:
cust.head()

,user_id,first_name,last_name,gender,state,age,date_joined,n_dependents,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [30]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,days_since_users_prior_order,product_id,add_to_cart_order,reordered,_merge,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spending,spending_flag,median_order_frequency,order_frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,both,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer

### Save Memory

In [32]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206209 non-null  int64
 1   first_name    206209 non-null  object
 2   last_name     206209 non-null  object
 3   gender        206209 non-null  object
 4   state         206209 non-null  object
 5   age           206209 non-null  int64
 6   date_joined   206209 non-null  object
 7   n_dependents  206209 non-null  int64
 8   fam_status    206209 non-null  object
 9   income        206209 non-null  int64
dtypes: int64(4), object(6)
memory usage: 15.7+ MB

In [33]:
cust['user_id']= cust['user_id'].astype('int32')
cust['age']= cust['age'].astype('int8')
cust['n_dependents']= cust['n_dependents'].astype('int8')
cust['income']= cust['income'].astype('int32')
cust['gender'] = cust['gender'].astype('category')
cust['fam_status'] = cust['fam_status'].astype('category')

In [34]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206209 non-null  int32
 1   first_name    206209 non-null  object
 2   last_name     206209 non-null  object
 3   gender        206209 non-null  category
 4   state         206209 non-null  object
 5   age           206209 non-null  int8
 6   date_joined   206209 non-null  object
 7   n_dependents  206209 non-null  int8
 8   fam_status    206209 non-null  category
 9   income        206209 non-null  int32
dtypes: category(2), int32(2), int8(2), object(4)
memory usage: 8.7+ MB

In [35]:
cust.head()

,user_id,first_name,last_name,gender,state,age,date_joined,n_dependents,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

Looks like values were not affected by truncating data types to be able to merge without data memory errors.

In [37]:
cust.describe()

             user_id            age   n_dependents         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 25 columns):
 #   Column                        Dtype
---  ------                        -----
 0   order_id                      int32
 1   user_id                       int32
 2   order_number                  int8
 3   orders_day_of_week            int8
 4   order_time_of_day             int8
 5   days_since_users_prior_order  float16
 6   product_id                    int32
 7   add_to_cart_order             int32
 8   reordered                     int8
 9   _merge                        category
 10  product_name                  object
 11  aisle_id                      int8
 12  department_id                 int8
 13  prices                        float64
 14  _prodMerge                    category
 15  price_range_loc               object
 16  busiest_day                   object
 17  busiest_days                  object
 18  busiest_period_of_day         object
 19  max_order                     int8
 20  loyalty_flag                  object
 21  avg_spending                  float64
 22  spending_flag                 object
 23  median_order_frequency        float16
 24  order_frequency_flag          object
dtypes: category(2), float16(2), float64(2), int32(4), int8(7), object(8)
memory usage: 3.3+ GB

In [39]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,days_since_users_prior_order,product_id,add_to_cart_order,reordered,_merge,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spending,spending_flag,median_order_frequency,order_frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,both,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,both,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,both,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-Frequent customer

Many of these can be category variables.

In [41]:
df['loyalty_flag']= df['loyalty_flag'].astype('category')
df['price_range_loc']= df['price_range_loc'].astype('category')
df['busiest_day']= df['busiest_day'].astype('category')
df['busiest_days']= df['busiest_days'].astype('category')
df['busiest_period_of_day']= df['busiest_period_of_day'].astype('category')
df['spending_flag']= df['spending_flag'].astype('category')
df['order_frequency_flag']= df['order_frequency_flag'].astype('category')

In [42]:
df.sort_values('user_id', inplace=True)
cust.sort_values('user_id', inplace=True)

Sorting can also help prevent Memory Errors when merging.

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32404859 entries, 0 to 32404858
Data columns (total 25 columns):
 #   Column                        Dtype
---  ------                        -----
 0   order_id                      int32
 1   user_id                       int32
 2   order_number                  int8
 3   orders_day_of_week            int8
 4   order_time_of_day             int8
 5   days_since_users_prior_order  float16
 6   product_id                    int32
 7   add_to_cart_order             int32
 8   reordered                     int8
 9   _merge                        category
 10  product_name                  object
 11  aisle_id                      int8
 12  department_id                 int8
 13  prices                        float64
 14  _prodMerge                    category
 15  price_range_loc               category
 16  busiest_day                   category
 17  busiest_days                  category
 18  busiest_period_of_day         category
 19  max_order                     int8
 20  loyalty_flag                  category
 21  avg_spending                  float64
 22  spending_flag                 category
 23  median_order_frequency        float16
 24  order_frequency_flag          category
dtypes: category(9), float16(2), float64(2), int32(4), int8(7), object(1)
memory usage: 2.1+ GB

### Merge

In [46]:
df_merged = df.merge(cust, on = 'user_id', indicator = '_custMerge')

In [47]:
df_merged.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_time_of_day,days_since_users_prior_order,product_id,add_to_cart_order,reordered,_merge,...,first_name,last_name,gender,state,age,date_joined,n_dependents,fam_status,income,_custMerge
0,2539329,1,1,2,8,NaN,196,1,0,both,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
1,3367565,1,6,2,7,19.0,25133,4,1,both,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
2,550135,1,7,1,9,20.0,196,1,1,both,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
3,550135,1,7,1,9,20.0,10258,2,1,both,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
4,550135,1,7,1,9,20.0,12427,3,1,both,...,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1718559,2,9,2,9,8.0,19156,12,1,both,...,Norma,Chapman,Female,Alaska,68,7/4/2017,3,married,64940,both
96,1718559,2,9,2,9,8.0,1559,13,1,both,...,Norma,Chapman,Female,Alaska,68,7/4/2017,3,married,64940,both
97,1718559,2,9,2,9,8.0,13351,14,0,both,...,Norma,Chapman,Female,Alaska,68,7/4/2017,3,married,64940,both
98,1718559,2,9,2,9,8.0,18523,15,1,both,...,Norma,Chapman,Female,Alaska,68,7/4/2017,3,married,64940,both
99,1718559,2,9,2,9,8.0,17872,16,1,both,...,Norma,Chapman,Female,Alaska,68,7/4/2017,3,married,64940,both

# 04 Export Data Frame

In [49]:
#df_merged_large.to_csv(os.path.join(path, '02 Data','Prepared Data', 'orders_products_combined.csv'))
df_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_custs.pkl'))